version: '2'
services:
    pool-app:
        image: pool
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://pool-mysql:3306/pool?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
    pool-mysql:
        extends:
            file: mysql.yml
            service: pool-mysql
